version: 2

sources:
  - name: jaffle_shop # ソースの論理名
    description: "基幹システムのデータベースからのデータ"
    database: ryusuke-sandbox # BigQuery Project ID: profiles.ymlの project と一致させる
    schema: dbt_tutorial      # BigQuery Dataset ID
    tables:
      - name: raw_customers       # BigQuery Table Name
        description: "顧客データの生テーブル"
      - name: raw_orders          # BigQuery Table Name
        description: "注文データの生テーブル"
        #loaded_at_field: order_date # 鮮度チェック用の日付カラム
        #freshness:
        #  warn_after: {count: 12, period: hour}
        #  error_after: {count: 24, period: hour}

  - name: stripe # 決済システムなど、別ソースの場合は分けるのが一般的
    description: "Stripeからの決済データ"
    database: ryusuke-sandbox
    schema: dbt_tutorial
    tables:
      - name: raw_payments
        description: "決済データの生テーブル"
